# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7042c453a91fe3f9400716261e36a75e67598ae229617beec968e3a9b395ce7cc42bae93e2f74b800fa5c9a15a64006248758f0f270a72af24d8630355f6bbd

test:
  secret_key_base: 43f7e9bb41eb42afa5b9380cc6ea1830aca0f2eaae683ad240deff2eed08ea354a08854469047d9e9130a2574b944be4e7e49bbe37a8f3e2b1baddf369ac1035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
